//! Server-side dispatch for Restate-hosted services.
//!
//! This module provides the machinery that lets a `BuiltService<...>` — the
//! same type used by the portable interpreter — act as the handler for a
//! Restate service endpoint. The binder generated by an adapter crate consumes
//! values of this type through the `RestateDispatch` trait.
//!
//! ## Design
//!
//! The same `HandlerList<C, H, Tail>` HList the portable path uses gets
//! traversed at runtime via [`HandleByName`], which matches an incoming
//! `CommandName` against each handler's `Command::NAME`, deserializes the
//! JSON payload, and invokes the handler. There is no parallel dispatch
//! ladder — Restate and portable share every routing decision.
//!
//! The factory shape is the only harness-specific piece: portable uses
//! `Fn() -> Future`, while Restate's factory receives `&Context<'_>`. That
//! shape difference is captured by [`RestateFactoryBridge`], which mirrors
//! the portable crate's `FactoryBridge` HRTB-on-`&F` pattern so the returned
//! future can borrow from both the factory value and the context for exactly
//! the call's scope.

use std::future::Future;
use std::pin::Pin;

use restate_sdk::context::Context;
use serde::de::DeserializeOwned;
use wee_events::{
    AggregateId, BuiltService, Command, CommandName, EmptyHandlers, Entity, HandlerBridge,
    HandlerList, LoaderBridge, Rejection,
};

use crate::service::ServiceResponse;

type BoxFuture<'a, T> = Pin<Box<dyn Future<Output = T> + Send + 'a>>;

// ---------------------------------------------------------------------------
// RestateFactoryBridge — lifetime-polymorphic factory-call glue.
//
// Mirrors `wee_events::FactoryBridge` but threads a `&'a Context<'a>` argument
// through to the factory. Implemented on `&'a F` so the returned future can
// borrow from both the factory value and the context for `'a`.
// ---------------------------------------------------------------------------

/// Bridge trait for factories that receive the Restate durable-execution
/// context. Implemented automatically for any `Fn(&Context<'_>) -> Future`.
#[doc(hidden)]
pub trait RestateFactoryBridge<'a, R>: Sized {
    fn call(f: Self, ctx: &'a Context<'a>) -> BoxFuture<'a, wee_events::Result<R>>;
}

impl<'a, R, F, Fut> RestateFactoryBridge<'a, R> for &'a F
where
    F: Fn(&'a Context<'a>) -> Fut,
    Fut: Future<Output = wee_events::Result<R>> + Send + 'a,
{
    fn call(f: Self, ctx: &'a Context<'a>) -> BoxFuture<'a, wee_events::Result<R>> {
        Box::pin(f(ctx))
    }
}

// ---------------------------------------------------------------------------
// HandleByName — name-first HList traversal.
//
// The portable path dispatches by type (`HandleCommand<C, Idx, ...>`); the
// Restate path dispatches by `CommandName` at runtime. Both traverse the same
// `HandlerList<C, H, Tail>` HList — this trait is the runtime-side twin.
// Each cons-cell impl requires `C: DeserializeOwned` so the JSON payload can
// be decoded before the handler is invoked.
// ---------------------------------------------------------------------------

/// Runtime name-first dispatch over a `HandlerList`. Returns `None` when no
/// handler matches the requested command name, letting the caller turn that
/// into a clean `Rejection` with the offending name in the message.
#[doc(hidden)]
pub trait HandleByName<Ctx, S>: Send + Sync {
    fn handle_by_name<'a>(
        &'a self,
        ctx: &'a Ctx,
        entity: &'a Entity<S>,
        name: &'a CommandName,
        command: serde_json::Value,
    ) -> BoxFuture<'a, wee_events::Result<Option<Entity<S>>>>;
}

impl<Ctx, S> HandleByName<Ctx, S> for EmptyHandlers
where
    Ctx: Send + Sync + 'static,
    S: Send + Sync + 'static,
{
    fn handle_by_name<'a>(
        &'a self,
        _ctx: &'a Ctx,
        _entity: &'a Entity<S>,
        _name: &'a CommandName,
        _command: serde_json::Value,
    ) -> BoxFuture<'a, wee_events::Result<Option<Entity<S>>>> {
        Box::pin(async move { Ok(None) })
    }
}

impl<C, H, Tail, Ctx, S> HandleByName<Ctx, S> for HandlerList<C, H, Tail>
where
    C: Command + DeserializeOwned + Send + 'static,
    Ctx: Send + Sync + 'static,
    S: Send + Sync + 'static,
    H: Send + Sync + 'static,
    for<'a> &'a H: HandlerBridge<'a, Ctx, S, C>,
    Tail: HandleByName<Ctx, S> + 'static,
{
    fn handle_by_name<'a>(
        &'a self,
        ctx: &'a Ctx,
        entity: &'a Entity<S>,
        name: &'a CommandName,
        command: serde_json::Value,
    ) -> BoxFuture<'a, wee_events::Result<Option<Entity<S>>>> {
        Box::pin(async move {
            if name.as_str() == <C as Command>::NAME {
                let cmd: C = serde_json::from_value(command)?;
                let updated =
                    <&H as HandlerBridge<'a, Ctx, S, C>>::call(&self.handler, ctx, entity, cmd)
                        .await?;
                Ok(Some(updated))
            } else {
                self.tail.handle_by_name(ctx, entity, name, command).await
            }
        })
    }
}

// ---------------------------------------------------------------------------
// RestateDispatch — the public trait consumed by Restate server binders.
// ---------------------------------------------------------------------------

/// Server-side dispatch surface for a Restate-hosted service.
///
/// Implemented via a single blanket impl over `BuiltService<...>` — the same
/// type the portable interpreter consumes. Adapter code (e.g. the Restate
/// server binder emitted by a future attribute macro) depends only on this
/// trait and can remain oblivious to the generic shape of the underlying
/// service.
pub trait RestateDispatch: Send + Sync {
    /// Load the current entity state for `id` using a per-request env
    /// constructed from `ctx` via the factory.
    fn load<'a>(
        &'a self,
        ctx: &'a Context<'a>,
        id: &'a AggregateId,
    ) -> BoxFuture<'a, wee_events::Result<ServiceResponse>>;

    /// Execute the named command against `target`, returning the updated
    /// state. Unknown command names return `Error::Rejection` with a
    /// `unknown_command` code.
    fn execute<'a>(
        &'a self,
        ctx: &'a Context<'a>,
        name: &'a CommandName,
        target: &'a AggregateId,
        command: serde_json::Value,
    ) -> BoxFuture<'a, wee_events::Result<ServiceResponse>>;
}

// ---------------------------------------------------------------------------
// Blanket impl — any `BuiltService` whose factory accepts `&Context` and
// whose handler HList implements `HandleByName` is automatically a
// `RestateDispatch`. No per-service codegen needed.
// ---------------------------------------------------------------------------

impl<R, S, L, F, H> RestateDispatch for BuiltService<R, S, L, F, H>
where
    R: Send + Sync + 'static,
    S: serde::Serialize + Send + Sync + 'static,
    L: Send + Sync + 'static,
    F: Send + Sync + 'static,
    H: HandleByName<R, S> + Send + Sync + 'static,
    for<'a> &'a L: LoaderBridge<'a, R, S>,
    for<'a> &'a F: RestateFactoryBridge<'a, R>,
{
    fn load<'a>(
        &'a self,
        ctx: &'a Context<'a>,
        id: &'a AggregateId,
    ) -> BoxFuture<'a, wee_events::Result<ServiceResponse>> {
        // Note: the factory and loader bridges are instantiated at inferred
        // inner lifetimes (shorter than `'a`) via HRTB, so the temporary `env`
        // value doesn't need to outlive the outer call scope.
        Box::pin(async move {
            let env = <&F as RestateFactoryBridge<'_, R>>::call(&self.factory, ctx).await?;
            let entity = <&L as LoaderBridge<'_, R, S>>::call(&self.loader, &env, id).await?;
            Ok(ServiceResponse {
                aggregate: entity.aggregate_id,
                revision: entity.revision,
                state: serde_json::to_value(&entity.state)?,
            })
        })
    }

    fn execute<'a>(
        &'a self,
        ctx: &'a Context<'a>,
        name: &'a CommandName,
        target: &'a AggregateId,
        command: serde_json::Value,
    ) -> BoxFuture<'a, wee_events::Result<ServiceResponse>> {
        Box::pin(async move {
            let env = <&F as RestateFactoryBridge<'_, R>>::call(&self.factory, ctx).await?;
            let entity = <&L as LoaderBridge<'_, R, S>>::call(&self.loader, &env, target).await?;
            let updated = self
                .handlers
                .handle_by_name(&env, &entity, name, command)
                .await?
                .ok_or_else(|| {
                    wee_events::Error::Rejection(Rejection::new(
                        "unknown_command",
                        format!("command '{}' is not handled by this service", name),
                    ))
                })?;
            Ok(ServiceResponse {
                aggregate: updated.aggregate_id,
                revision: updated.revision,
                state: serde_json::to_value(&updated.state)?,
            })
        })
    }
}
